'use strict';
//debugger;
var ageofshimrod = ageofshimrod || {};

ageofshimrod.C = Object.freeze({
  UI_BORDER_COLOR : "#191970",
  UI_RECT_COLOR : "#E6E6FA",
  UI_FONT_COLOR : "#191970",
  UI_BORDER_RED : "#f81a2d",
  COLOR_CONTEXTUAL : "#2F4f4f",
  COLOR_TEXT : "#deebf8",
  COLOR_TEXT_CHOOSEN : "#5EB6DD",
  COLOR_TURQUOISE : "#bdffff",

  UI_STATUS_SHOW : 0,
  UI_STATUS_HIDDEN : 1,

  CLICK_ON_WINDOW : true,
  CLICK_OUTSIDE_WINDOW : false,

  RESSOURCE_PIERRE : 1,
  RESSOURCE_BOIS : 2,
  RESSOURCE_FOOD : 3,

  DECOR_PIERRE : 0,
  DECOR_ARBRE : 1,
  DECOR_ARBRE_MORT : 1,

  BUILDING_HOUSE : 0,
  BUILDING_LUMBER : 1,
  BUILDING_MINEUR : 2,
  BUILDING_ARMY : 3,
  BUILDING_FARM : 4,

  MESSAGE_ALERT_INFO : "#deebf8",
  MESSAGE_ALERT_WARNING : "#FE9A2E",
  MESSAGE_ALERT_HIGH : "#FA5858",

  BUTTON_STATUS_KO : 0,
  BUTTON_STATUS_OK : 1,

  PEON_STATUS_COLLECT : 0,
  PEON_STATUS_GOTO_RESSOURCE : 1,
  PEON_STATUS_GOTO_AFFECTATION : 2,
  PEON_STATUS_WAIT : 3,
  PEON_STATUS_SEARCH_ENNEMY : 4,
  PEON_STATUS_GOTO_ENNEMY : 5,
  PEON_STATUS_ATTACK_ENNEMY : 6,

  PEON_ATTACK_SPEED : 200,
  PEON_HEALING_SPEED : 1000,

  CHARACTER_STEP : 3,

  DIRECTION_UP :3,
  DIRECTION_DOWN :0,
  DIRECTION_LEFT :1,
  DIRECTION_RIGHT :2,

  MAP_STATUS_NORMAL : 0,
  MAP_STATUS_ADD_BUILDING : 1,

  GAME_STATUS_MAINMENU : 4,
  GAME_STATUS_START : 0,
  GAME_STATUS_INGAME : 1,
  GAME_STATUS_ENDGAME_WIN : 2,
  GAME_STATUS_ENDGAME_LOSE : 3,

  EDITOR_STATUS_NONE : 0,
  EDITOR_STATUS_ADD_DECOR : 1,
  EDITOR_STATUS_REMOVE_DECOR : 2,

  RECORD_RECOLT :0,

  OBJECTIF_STATUS_INPROGRESS : 0,
  OBJECTIF_STATUS_DONE : 1,

  ANIMATION_SPEED : 50,
  COLLECT_SPEED : 100,

  ANIMATION_BLOOD : 2,

  MONSTER_STATUS_GOTO_TARGET : 0,
  MONSTER_STATUS_ATTACK : 1,
  MONSTER_ATTACK_SPEED : 300,

});
